/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.ControladorAdministrador;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author FABIO
 */
public class CadastrarApostador extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarGestor
     */
    public CadastrarApostador() {
        initComponents();
        setIcon();
        jCampoMat.setDocument(new Documento1());
        jCampoPesqMatGer.setDocument(new Documento1());
        desabilitarBotoes();
        desabilitarCampos();
    }
private void desabilitarBotoes(){
    BtnNovo.setEnabled(true);
    BtnSalvar.setEnabled(false);
    BtnCancelar.setEnabled(false);
    
   
   } 
   
   private void habilitarBotoes(){
    BtnNovo.setEnabled(false);
    BtnSalvar.setEnabled(true);
    BtnCancelar.setEnabled(true);
   }
   private void desabilitarCampos(){
    jCampoNome.setEnabled(false);
    jCampoMat.setEnabled(false);
    jCampoSetor.setEnabled(false);
    jCampoCargo.setEnabled(false);
    jCampoSenhaGestor.setEnabled(false);
    jCampoNome.setText("");
    jCampoMat.setText("");
    jCampoSetor.setText("");
    jCampoCargo.setText("");
    jCampoSenhaGestor.setText("");
   } 
   
   private void habilitarCampos(){
   jCampoNome.setEnabled(true);
    jCampoMat.setEnabled(true);
    jCampoSetor.setEnabled(true);
    jCampoCargo.setEnabled(true);
    jCampoSenhaGestor.setEnabled(true);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCampoNome = new javax.swing.JTextField();
        jCampoMat = new javax.swing.JTextField();
        jCampoSetor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCampoCargo = new javax.swing.JTextField();
        BtnNovo = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jBtnPesqGestor = new javax.swing.JButton();
        jCampoPesqMatGer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBtnExcluir = new javax.swing.JButton();
        BtnPesqCanc = new javax.swing.JButton();
        jCampoFunc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCampoSenhaGestor = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jCampoSenhaGestor1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        jLabel4.setText("End.");

        jLabel5.setText("Telefone");

        BtnNovo.setText("Novo");
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });

        BtnSalvar.setText("Salvar");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        BtnEditar.setText("Editar");

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("PESQUISAR APOSTADOR");

        jBtnPesqGestor.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jBtnPesqGestor.setText("OK");
        jBtnPesqGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesqGestorActionPerformed(evt);
            }
        });

        jCampoPesqMatGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCampoPesqMatGerActionPerformed(evt);
            }
        });

        jLabel8.setText("CPF");

        jLabel7.setText("Apostador");

        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        BtnPesqCanc.setText("Cancelar");
        BtnPesqCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesqCancActionPerformed(evt);
            }
        });

        jCampoFunc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCampoFunc.setForeground(new java.awt.Color(0, 0, 204));

        jLabel9.setText("Usuário");

        jLabel10.setText("Senha");

        jCampoSenhaGestor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCampoSenhaGestor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jCampoPesqMatGer, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnPesqGestor))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                        .addComponent(BtnPesqCanc))
                                    .addComponent(jCampoFunc)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(BtnNovo)
                            .addGap(18, 18, 18)
                            .addComponent(BtnSalvar)
                            .addGap(18, 18, 18)
                            .addComponent(BtnEditar)
                            .addGap(18, 18, 18)
                            .addComponent(BtnCancelar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel9)
                                .addComponent(jLabel2)
                                .addComponent(jLabel10))
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCampoNome)
                                .addComponent(jCampoCargo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jCampoSetor, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jCampoMat)
                                .addComponent(jCampoSenhaGestor)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCampoSenhaGestor1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCampoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCampoSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCampoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCampoSenhaGestor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCampoSenhaGestor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNovo)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnEditar)
                    .addComponent(BtnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCampoPesqMatGer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesqGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCampoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnExcluir)
                    .addComponent(BtnPesqCanc))
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
    habilitarBotoes();
    habilitarCampos();
    }//GEN-LAST:event_BtnNovoActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
    desabilitarBotoes();
    desabilitarCampos();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
    String mat = jCampoMat.getText();
    int campoMat = Integer.parseInt(mat);
    ControladorAdministrador.inserir_Gestor(jCampoNome.getText(), jCampoSenhaGestor.getText(), campoMat, jCampoSetor.getText(), jCampoCargo.getText());
      
            ControladorAdministrador.backup_gerente();
       
    desabilitarBotoes();
    desabilitarCampos();
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnPesqCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesqCancActionPerformed
           jCampoFunc.setText("");
           jCampoPesqMatGer.setText("");
    }//GEN-LAST:event_BtnPesqCancActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
    String mat = jCampoPesqMatGer.getText();
    int campoMat = Integer.parseInt(mat);
    ControladorAdministrador.excluir_Gestor(campoMat);
           jCampoFunc.setText("");
           jCampoPesqMatGer.setText("");
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnPesqGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesqGestorActionPerformed
        String mat = jCampoPesqMatGer.getText();
        int campopesqMat = Integer.parseInt(mat);
        ControladorAdministrador.pesquisa_Gestor(campopesqMat);
    }//GEN-LAST:event_jBtnPesqGestorActionPerformed

    private void jCampoPesqMatGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCampoPesqMatGerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCampoPesqMatGerActionPerformed

    private void jCampoSenhaGestor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCampoSenhaGestor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCampoSenhaGestor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarApostador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarApostador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarApostador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarApostador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarApostador().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnPesqCanc;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnPesqGestor;
    private javax.swing.JTextField jCampoCargo;
    public static javax.swing.JTextField jCampoFunc;
    private javax.swing.JTextField jCampoMat;
    private javax.swing.JTextField jCampoNome;
    private javax.swing.JTextField jCampoPesqMatGer;
    private javax.swing.JPasswordField jCampoSenhaGestor;
    private javax.swing.JPasswordField jCampoSenhaGestor1;
    private javax.swing.JTextField jCampoSetor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         
        this.setIconImage(new ImageIcon(getClass().getResource("/janelas/relogio_ponto.png")).getImage());
    }
    
}
class Documento1 extends PlainDocument{

      public void insertString(int offs, String str, AttributeSet a)throws BadLocationException {
          int tamanho= (this.getLength()+ str.length());
          if(tamanho<=7){
             super.insertString(offs, str.replaceAll("[aA-zZ]", ""), a);
          }
          else{    
            super.insertString(offs, str.replaceAll("[aA0-zZ9]", ""), a);
          }
      }
}